"""add seller description

Revision ID: 97aaf2bc63c0
Revises: 608250917019
Create Date: 2026-03-17 18:21:35.729448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97aaf2bc63c0'
down_revision: Union[str, None] = '608250917019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'description')
    # ### end Alembic commands ###
